### ISSUE TITLE
BankControllerTest doTransfer fail

### ISSUE THREAD

**Issue by brunolmourao** [TPII20162/BankSys#10]
O método doTransfer() da classe BankController não funciona corretamente  
![transfer](https://cloud.githubusercontent.com/assets/22860385/19701241/4a3045e8-9ad9-11e6-8da8-633f57dca76e.png)

**Comment by falquinho** [comment]
Bug na linha 96 do arquivo BankController.Java
É so mudar "fromNumber" para "toNumber"
