### ISSUE TITLE
Refatoração da interface ClientServices

### ISSUE THREAD

**Issue by andgomes** [TPII20162/BankSys#104]
Nos métodos relacionados às transações doDebit(), doCredit() e doTransfer() os tipos dos parâmetros são Client(referência para um objeto Client), String(número da conta) e Double(saldo a ser creditado, debitado ou transferido).
A minha ideia de refatoração era mudar a assinatura para que apenas os parâmetros Account e Balance fossem passados para o método.
A assinatura ficaria assim:

public void doDebit(Account, Double)
public void doCredit(Account, Double)
public void doTransfer(Account, Double)

Dessa forma, o tamanho da assinatura dos métodos seria reduzida.
Notem que todas as informações anteriores ainda estarão acessíveis:
Recuperar o cliente: Account.getClient()
Recuperar o número da conta: Account.getNumber()

Aceito sugestões. Se não houver nenhuma objeção e alguém quiser fazer essa refatoração, sinta-se à vontade.

**Comment by MarianaFL** [comment]
Parece razoável pra mim

**Comment by ivensdenner** [comment]
Vou fazer essa refatoração
