### ISSUE TITLE
Implementar método create do ClientDatabaseDAO.

### ISSUE THREAD

**Issue by 99heitor** [TPII20162/BankSys#109]

**Comment by 99heitor** [comment]
Create está com erro que me parece ser na configuração do banco de dados. 
Ele funciona, mas ao testar se comporta de forma incosistente e o terminal lança a seguinte mensagem:
`Could not create client on database: [SQLITE_READONLY]  Attempt to write a readonly database (attempt to write a readonly database)`

**Comment by fscfelipe** [comment]
Também acho que deve ser algo relacionado à tabela, pois se não me engano, quando fiz uns testes aqui, o teste para o método create() ou delete() quando executados isoladamente, passam ( :+1:) , mas se você tentar executar a classe de testes com os métodos create() e delete() juntos, ai um dos dois irão falhar (:-1: ) . E esse erro do banco surge.
