### ISSUE TITLE
Método ClientServicesException.doLogin() deveria lançar uma ClientServiceException

### ISSUE THREAD

**Issue by andgomes** [TPII20162/BankSys#118]
Encontrei o bug ao tentar logar no menu de cliente sem nenhum cliente ter sido criado.
Quando um cliente tenta fazer login, ele fica preso na tela de login sem conseguir voltar para a tela
inicial.
Fui procurar qual era o problema e descobri que o método ClientView.doLogin() espera uma ClientServiceException caso o username ou o password não estejam corretos. O bloco catch dessa exceção faz com que o usuário volte para a tela inicial.
Isso não está acontecendo atualmente por que a implementação do método ClientServicesImpl.doLogin() captura a ClientServiceException ao invés de lançá-la.
Quem quiser fixar esse bug pode fazer o seguinte: ao invés de capturada no método ClientServicesImpl.doLogin(), a ClientServiceException deve ser lançada. Depois disso, a verificação se o client é null será desnecessária, bastando retornar o client.

**Comment by lucasvasconcelos8** [comment]
@andgomes eu fui olhar o problema, e vi que a exceção "ClientServiceException" parece não ter influência no problema, e que na verdade a exceção importante é "ClientNotFoundException". E quando não captura ela, em vez de voltar para tela inicial, ele solta um erro.

**Comment by lucasvasconcelos8** [comment]
@andgomes vi como consertar, confere ai. E ignora as mudanças na classe de test que tiver, foi um erro, e eu corrigi com outro commit 👍
