### ISSUE TITLE
Operador pode criar conta para um cliente inexistente

### ISSUE THREAD

**Issue by andgomes** [TPII20162/BankSys#122]
No menu do operador, há a opção "New Account".
Ao escolher essa opção, o sistema pede para o operador informar o id do cliente.
Quando um id inexistente é inserido, o sistema cria a conta normalmente, quando
o que deveria acontecer era mostrar uma mensagem informando que o cliente
não está cadastrado e não permitir a criação da conta.

**Comment by falquinho** [comment]
Vou dar uma olhada
