### ISSUE TITLE
Bad Smell: Classe BankController: muitas reponsabilidades

### ISSUE THREAD

**Issue by falquinho** [TPII20162/BankSys#15]
A classe BankController do pacote banksys.control atualmente é responsável por manter registro das contas e realizar transações entre elas.
Recomendo dividir em BankController e FinancialController. 
A nova classe seria a responsável pelas transferencias, debito etc.

**Comment by tjbruno** [comment]
Além disso, acho que uma maneira de deixar o controller mais limpo seria tirar toda a lógica de dentro dele, deixando ele responsável apenas pela comunicação entre a view e a aplicação.

Uma maneira que geralmente isso é feito é criar um pacote separado contendo os casos de uso.
Por exemplo, o `doTransfer` viraria uma classe interface `ITransferService`, que poderia implementada de diverças maneiras.

Além disso, ficaria mais simples o teste e o reuso dentro da aplicação

https://8thlight.com/blog/uncle-bob/2012/08/13/the-clean-architecture.html

http://fideloper.com/hexagonal-architecture

**Comment by fscfelipe** [comment]
Comecei a fazer a refatoração. Utilizei o JDeodorant, Extrai uma classe, e dividi em FinancialController e BankController, como propôs @falquinho . Acho que ainda da pra refatorar mais coisas..

**Comment by igorsbrito** [comment]
A classe FinancialController já esta pronta? Começarei a fazer o test Unitário dela.

**Comment by andgomes** [comment]
A classe FinancialController tem a responsabilidade de adicionar e remover contas. Acho que só deveria ter a responsabilidade de fazer transações entre contas.

**Comment by fscfelipe** [comment]
@andgomes é preciso refatorar esses métodos. Esse resultado ai da classe extraida, foi o padrão dado pelo JDeodorant.

**Comment by fscfelipe** [comment]
Vou fechar essa issue. Seria bom criar outras para resolver o bad smell de método que ainda ficou na nova classe extraída.
