### ISSUE TITLE
Bad Smell: banksys.view.ATM24H

### ISSUE THREAD

**Issue by falquinho** [TPII20162/BankSys#16]
O método main da classe ATM24H:
    -tem muitas responsabilidades
    -é gigante
    -tem switches aninhados

Tem que ser refatorada.
Sugiro uma Classe responsável por apenas imprimir menus e fazer transição
a partir de entrada do usuário (uma máquina de estado)

**Comment by MarianaFL** [comment]
Estou estudando soluções, vendo o que/como fazer.

**Comment by 99heitor** [comment]
Eu e a Mariana vamos pesquisar e tentar desenvolver uma interface gráfica, como descrito no backlog, ao invés de tentar refatorar a interface de texto existente.

**Comment by falquinho** [comment]
Eu vou refatorar a Interface Terminal por enquanto.

**Comment by ivensdenner** [comment]
@falquinho Refatorar como?

**Comment by 99heitor** [comment]
Pela dica do professor, talvez seguir com a interface gráfica no momento não seja uma boa ideia. Acho que é melhor refatorar a interface de texto primeiro. Com uma separação mais detalhada dos problemas podemos até trabalhar ao mesmo tempo nisso.

**Comment by falquinho** [comment]
Terminei minha refatoração (faz tempo já). Ela esta no meu github: https://github.com/falquinho/MyBankSys/tree/development/src/banksys/view

Dêem uma olhada. Eu vou ver aqui se dá pra integrar na refatoração que o Prof. fez no sistema.

**Comment by falquinho** [comment]
Também fiz mockup de GUI. Coisa pouca, so pra sentir como seria....
![sugestao_gui](https://cloud.githubusercontent.com/assets/14141017/20192079/1303a0f2-a767-11e6-80c1-51c8494616d4.png)

**Comment by falquinho** [comment]
Fiz refatoração na nova arquitetura. Dêem uma olhada. Se concordatem já posso comitar.
https://github.com/falquinho/MyBankSys

**Comment by andgomes** [comment]
Acho que a maior parte dos bad smells dessa classe foram removidos no commit ef55c8fa4e1413b3e0baad848db92ad13a4e3c1f
