### ISSUE TITLE
Método testCreditNegativeAmount()

### ISSUE THREAD

**Issue by andgomes** [TPII20162/BankSys#17]
O método testCreditNegativeAmount da classe AbstractAccountTest falha mesmo quando era pra passar. O objetivo do teste é lançar a exceção NegativeAmountException, ou seja, se lançar a exceção o teste é pra passar. Mas a exceção está sendo capturada e o método chama o Assert.fail().
Bug introduzido no commit 1157c948727df4a93fab339a72ad4acba0fade7c

**Comment by lucasvasconcelos8** [comment]
@andgomes estou dando uma olhada e já mandou um commit com a correção

**Comment by lucasvasconcelos8** [comment]
@andgomes você está mexendo na classe?

**Comment by liviolima** [comment]
Opa. Eu consertei o que o @andgomes falou.

**Comment by lucasvasconcelos8** [comment]
Aviso antes poxa, deu altos conflitos para mim aqui. Enfim

**Comment by liviolima** [comment]
Okay. Foi mal @lucasvasconcelos8

**Comment by andgomes** [comment]
O bug ainda não foi fixado. Rodei o teste de novo e ainda não tá passando. O problema é a lógica do método de teste, não o valor que é passado para o método credit.

**Comment by liviolima** [comment]
Estranho. Vou ver...

**Comment by liviolima** [comment]
Pronto. Dá uma olhada.

**Comment by andgomes** [comment]
Issue closed in 7c8f77a66e783a532e12ae992627d4be0424b5b3
