### ISSUE TITLE
Refatoração do Design das classes Controller para o padrão de projeto facade

### ISSUE THREAD

**Issue by lcarvalhoufc** [TPII20162/BankSys#19]
A idéia é que se faça uma refatoração do design utilizando o padrão de projeto facade.

**Comment by fscfelipe** [comment]
No caso seriam 3 classes. 2 de serviços, e 1 de fachada para acessar uma das classes de serviço.
Isso foi necessário por causa da refatoração como Leandro citou ai em cima.

**Comment by andgomes** [comment]
Issue separada em três: #20 #21 #22
