### ISSUE TITLE
Criar classe de serviço AccountService

### ISSUE THREAD

**Issue by andgomes** [TPII20162/BankSys#20]
Copiar os métodos relacionados à criação de contas da classe BankController para essa classe.

**Comment by ivensdenner** [comment]
@brunolmourao Teria como adicionar um método de addAccount que receba como parâmetro o número da conta e o tipo da conta que deva ser criada (usando um enum, por exemplo) nesta nova classe? Estavamos discutindo sobre a refatoração da classe ATM24H e vimos que método desses na AccountService seria útil, pois assim a conta não precisaria ser instanciada na ATM.

**Comment by brunolmourao** [comment]
Posso tentar fazer isso .

**Comment by ivensdenner** [comment]
Sugiro criar o seguinte enum:

```java
enum AccountType {
    ORDINARY_TYPE, SAVINGS_ACCOUNT, SPECIAL_ACCOUNT, TAX_ACCOUNT
}
```

Para ser utilizado como parâmetro quando for solicidade a criação de uma conta pela interface.

**Comment by brunolmourao** [comment]
Crio para o método retrive também?

**Comment by ivensdenner** [comment]
Acredito que não é necessário, já que o retrieve já retorna uma AbstractAccount.

**Comment by ivensdenner** [comment]
As modificações não estão no commit 56ac067

**Comment by brunolmourao** [comment]
Criei a classe AccountService com o método addAccount utilizando enum , mas não exclui os métodos da classe BankController
