### ISSUE TITLE
Criar o comando “Sacar” (Withdraw) no menu para sacar dinheiro de uma conta

### ISSUE THREAD

**Issue by edmilsonrobson** [TPII20162/BankSys#25]
Criar o comando "Withdraw" (sacar) no menu. O comando de "Withdraw" terá a mesma lógica do "Debit" (sem substituí-lo), mas será incrementado posteriormente com opções de cédulas que o usuário deseja receber para o saque (a ser realizado em uma issue posterior)

**Comment by lucasvasconcelos8** [comment]
Vou fazer
