### ISSUE TITLE
Algoritmos para decisão de número e valor de cédulas de saque

### ISSUE THREAD

**Issue by edmilsonrobson** [TPII20162/BankSys#27]
Relacionado com a issue #25 e #26.

Criação de uma classe BankNoteController no pacote BankSys.BankNote responsável pelos algoritmos de seleção de número e valor de cédulas de saque.

É muito interessante utilizar o padrão Strategy para definir qual estratégia para a seleção das cédulas.

Inicialmente, será implementado apenas a estratégia de pegar o menor número de cedulas. Caso o usuário saque 55 reais, por exemplo, esse algoritmo retornaria "1 de 50, 1 de 5".

Note que as cédulas existentes são as de 2, 5, 10, 20 e 50 (#26) e são, atualmente, infinitas. Isso pode mudar no futuro.

**Comment by edmilsonrobson** [comment]
Por algum motivo o github não me reconhece como autor dos commits (mesmo eu setando no git config), mas eu sou o commit #5f37b8b

**Comment by liviolima** [comment]
Feito.
