### ISSUE TITLE
Accounts unit tests failures

### ISSUE THREAD

**Issue by IgorLimaKI** [TPII20162/BankSys#3]
O sistema falhou em diversos testes unitários, mais detalhes na imagem em anexo.
![tec](https://cloud.githubusercontent.com/assets/22954346/19614432/7ecd93b6-97cb-11e6-8b44-a90f1b6d8140.jpg)

**Comment by MarianaFL** [comment]
Issue consertada pelos commits:
3488100dc5767b45ec333cfb066c10f28d5d868d 
0394b418e878879f7117941033917bf3b5a5da37
