### ISSUE TITLE
Implementar método ClientServicesImpl.doTransfer

### ISSUE THREAD

**Issue by andgomes** [TPII20162/BankSys#43]

**Comment by LucasFalcao** [comment]
O método doTransfer vai consistir basicamente de:
-Checar se a conta alvo existe
-Debitar da Conta Fonte
-Creditar na Conta Destino

A primeira checagem é repetida no método de creditar, mas é "necessária" pra evitar problemas de debitar na conta fonte e a conta destino não existir, então, da forma que está implementado, teríamos que reverter a operação de débito.

Também não sei se estou usando o tratamento de Exceções da forma certa.

Caso alguém tenha alguma sugestão ou ideia melhor, sinta-se livre para fazer.
