### ISSUE TITLE
Teste para o método AccountInMemoryDAO.delete

### ISSUE THREAD

**Issue by IgorLimaKI** [TPII20162/BankSys#76]

**Comment by andgomes** [comment]
O teste tenta deletar uma conta passando o número 2, mas nada garante que alguma das três contas terá o número 2(por exemplo, se mais de três contas tiverem sido criadas em outros testes, o próximo número a ser atribuído é o 4). Por esse motivo, algumas vezes o teste passa e outras vezes não passa. Issue reaberta.
