### ISSUE TITLE
Definir schema da base de dados e implementar este schema no banco de dados sqlite

### ISSUE THREAD

**Issue by rodriguesmoises** [TPII20162/BankSys#92]
Criar o esquema do banco(Tabelas, colunas, chaves...) e criar um arquivo schema_banksys.db com as tabelas do banco.

**Comment by rodriguesmoises** [comment]
Criado o template do schema do banco de dados.
nome das chaves primárias: <tabela_id>
Continuei com o mesmo tipo dos dados que tinham nas classes

Segue o SQL que criação das tabelas:
CREATE TABLE "account" ("number" VARCHAR, "balance" DOUBLE, "account_type" VARCHAR, "client_id" DOUBLE PRIMARY KEY  NOT NULL , "bonus" DOUBLE)

CREATE TABLE "user" ("user_id" DOUBLE PRIMARY KEY  NOT NULL  UNIQUE , "full_name" VARCHAR, "user_name" VARCHAR, "password" VARCHAR)

CREATE TABLE "log" ("log_id" INTEGER PRIMARY KEY  NOT NULL  UNIQUE , "user_id" DOUBLE, "account_number" VARCHAR, "date" TEXT)

CREATE TABLE "client" ("user_id" DOUBLE PRIMARY KEY  NOT NULL  UNIQUE )

CREATE TABLE "operator" ("user_id" DOUBLE PRIMARY KEY  NOT NULL  UNIQUE )

**Comment by 99heitor** [comment]
Olá, tenho algumas dúvidas em relação ao schema. Estou implementando os métodos do `ClientDatabaseDAO` e queria saber de umas coisas.

- No método` create()` é necessário criar duas entradas no banco de dados, uma na tabela `client` e uma na tabela `user`? Se for o caso, eu teria que me preocupar com a atomicidade dessa operação (só poder completar as duas ou nenhuma). O mesmo questionamento pro método `retrieve`.
- A busca por client é feita no método `retrieveByUsernameAndPassword`, mas no schema o user_name não é UNIQUE. Isso não poderia ser um problema?
- A tabela `account` tem uma primary key chamada `client_id`. Ela deve coincidir com `user_id`s da tabela `client`, correto?

As dúvidas surgiram mais da minha falta de prática com implementação de DAO, então posso ter falado alguma besteira.

**Comment by rodriguesmoises** [comment]
Opa, 
Sim, é necessário inserir duas tuplas na base: uma em client e uma em user.
Deveria preocupar-se com a atomicidade sim, opções:
O método preparedStatement.executeUpdate() retorna um int com o tamanho de linhas alteradas, no caso da inserção correta, retorna 1. Então você, na implementação do metodo create(Client) chama o metodo create(User) e pega o retorno do método, só tenta salvar em client se estiver salvo em user.
Mas para isto você precisaria mudar o retorno do método(também na interface e na forma em memória).

Outra forma mais simples: caso o preparedStatement.executeUpdate() em create(User) retorne 0, você seta o retorno como null. Precisa tratar isto(possivel NullPointerException) nas chamadas do método. Aconselho esta abordagem.

**Comment by rodriguesmoises** [comment]
"A busca por client é feita no método retrieveByUsernameAndPassword, mas no schema o user_name não é UNIQUE. Isso não poderia ser um problema?"

Vou alterar para unique quando chegar em casa. Mas caso existam mais de um caso com o mesmo username e password o método retrieve irá recuperar apenas quem foi salvo primeiro.
Teoricamente o segundo username (que seria impedido de entrar na tabela) não será retornado, já que o resultSet retorna as tuplas em sequência.

**Comment by rodriguesmoises** [comment]
"A tabela account tem uma primary key chamada client_id. Ela deve coincidir com user_ids da tabela client, correto?"

Eu fiz uma alteração na base e commitei semana passada. Removi a primary key(um cliente pode ter mais de uma conta). A coluna que deve ser UNIQUE é a number, não sei se o SQLite aceita VARCHAR como PK. Vou pelo menos deixar UNIQUE. Não vai atrapalhar nada na implementação dos DAO's.

Mas o client_id deve coincidir com o client_id e com o user_id a tabela user.

PS: Ótimas observações! ;)

**Comment by 99heitor** [comment]
Obrigado pelas dicas!
